// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SynapsePENS.Api.Data;

#nullable disable

namespace SynapsePENS.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216155449_InitialFinalProject")]
    partial class InitialFinalProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SynapsePENS.Api.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Menunggu Persetujuan");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("StudentId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SynapsePENS.Api.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            RoomName = "C 101"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            RoomName = "C 102"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            RoomName = "C 103"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            RoomName = "C 104"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            RoomName = "C 105"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 30,
                            RoomName = "C 106"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 30,
                            RoomName = "C 201"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 30,
                            RoomName = "C 202"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 30,
                            RoomName = "C 203"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 30,
                            RoomName = "C 204"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 30,
                            RoomName = "C 205"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 120,
                            RoomName = "SAW-03.06"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 120,
                            RoomName = "SAW-06.08"
                        });
                });

            modelBuilder.Entity("SynapsePENS.Api.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NRP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SynapsePENS.Api.Entities.Booking", b =>
                {
                    b.HasOne("SynapsePENS.Api.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SynapsePENS.Api.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
